# Generated by Django 5.1.4 on 2025-01-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='initial_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='current_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='turn',
            name='state_after_turn',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
