# Generated by Django 5.1.4 on 2025-01-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_simulation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='prompt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
