# Generated by Django 5.1.4 on 2025-01-23 15:56

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_simulation_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='prompt',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='environment',
            name='initial_state',
            field=models.JSONField(blank=True, default=dict, validators=[main.models.validate_json_size]),
        ),
        migrations.AlterField(
            model_name='environment',
            name='rules',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='current_state',
            field=models.JSONField(blank=True, default=dict, validators=[main.models.validate_json_size]),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='prompt',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='turn',
            name='input_data',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='turn',
            name='output_data',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='turn',
            name='state_after_turn',
            field=models.JSONField(blank=True, default=dict, validators=[main.models.validate_json_size]),
        ),
    ]
